name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List repository contents
        run: ls -R .

      - name: Run pytest
        run: python -m pytest --maxfail=1 --disable-warnings -q

  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & tag image
        run: |
          IMAGE=realfusion/ticketsystemapplication
          docker build . \
            --file Dockerfile \
            --tag $IMAGE:${{ github.sha }}

      - name: List Docker images
        run: docker images

  deploy:
    name: Push to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image tags
        run: |
          IMAGE=realfusion/ticketsystemapplication
          docker push $IMAGE:${{ github.sha }}
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest

      - name: Confirm pushed tags
        run: echo "✅ Pushed tags for $IMAGE"
