name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # … your existing test job …

  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & tag image
        run: |
          IMAGE=realfusion/ticketsystemapplication
          docker build . \
            --file Dockerfile \
            --tag $IMAGE:${{ github.sha }}

      - name: List Docker images
        run: docker images

  deploy:
    name: Push to Docker Hub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image tags
        run: |
          IMAGE=realfusion/ticketsystemapplication
          # Push the SHA-tagged image
          docker push $IMAGE:${{ github.sha }}
          # Tag as latest and push
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest

      - name: Confirm pushed tags
        run: |
          echo "Pushed tags for $IMAGE"
